#!/usr/bin/env bash
# =============================================================================
# add_device.sh
#
# Interactive helper to add a new Chromebook codename to the build system.
# Detects the current hardware, determines platform, and creates the device
# config fragment and hardware_map entry.
#
# Usage: sudo ./add_device.sh [--codename NAME] [--platform PLATFORM]
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

CODENAME="${1:-}"
PLATFORM="${2:-}"

log() { echo "[add_device] $*"; }

# --- Auto-detect if not provided ---
if [[ -z "$CODENAME" ]]; then
    if command -v cros_config &>/dev/null; then
        CODENAME=$(cros_config / name 2>/dev/null | tr '[:upper:]' '[:lower:]' || true)
    fi
    if [[ -z "$CODENAME" ]]; then
        CODENAME=$(cat /sys/class/dmi/id/board_name 2>/dev/null | tr '[:upper:]' '[:lower:]' || true)
    fi
    log "Detected codename: $CODENAME"
fi

# --- Check if already in map ---
if grep -q "^${CODENAME}|" "${REPO_DIR}/configs/hardware_map.conf"; then
    log "Codename '$CODENAME' already exists in hardware_map.conf"
    grep "^${CODENAME}|" "${REPO_DIR}/configs/hardware_map.conf"
    exit 0
fi

# --- Determine platform from CPU ---
if [[ -z "$PLATFORM" ]]; then
    cpu_vendor=$(grep -m1 vendor_id /proc/cpuinfo | awk '{print $3}')
    cpu_family=$(grep -m1 "cpu family" /proc/cpuinfo | awk '{print $4}')
    cpu_model_name=$(grep -m1 "model name" /proc/cpuinfo | cut -d: -f2 | xargs)
    
    log "CPU: $cpu_model_name (vendor=$cpu_vendor family=$cpu_family)"
    
    if [[ "$cpu_vendor" == "AuthenticAMD" ]]; then
        if [[ "$cpu_family" == "21" ]]; then
            PLATFORM="amd-stoneyridge"
        elif echo "$cpu_model_name" | grep -qiE "Ryzen|Athlon.*Gold|Athlon.*Silver"; then
            PLATFORM="amd-ryzen-zork"
        else
            PLATFORM="amd-ryzen-zork"
        fi
    elif [[ "$cpu_vendor" == "GenuineIntel" ]]; then
        # Try to determine Intel generation from model name
        if echo "$cpu_model_name" | grep -qiE "10th|Core.*10[0-9][0-9][0-9]U"; then
            PLATFORM="intel-cometlake"
        elif echo "$cpu_model_name" | grep -qiE "11th|Core.*11[0-9][0-9][0-9]"; then
            PLATFORM="intel-tigerlake"
        elif echo "$cpu_model_name" | grep -qiE "12th|Core.*12[0-9][0-9][0-9]"; then
            PLATFORM="intel-alderlake"
        else
            PLATFORM="intel-cometlake"
            log "WARNING: Cannot determine exact Intel generation, defaulting to cometlake"
        fi
    fi
    log "Detected platform: $PLATFORM"
fi

# --- Detect codec ---
CODECS=()
if command -v aplay &>/dev/null; then
    if aplay -l 2>/dev/null | grep -qi "da7219"; then CODECS+=("da7219"); fi
    if aplay -l 2>/dev/null | grep -qi "max98357"; then CODECS+=("max98357a"); fi
    if aplay -l 2>/dev/null | grep -qi "rt5682"; then CODECS+=("rt5682"); fi
    if aplay -l 2>/dev/null | grep -qi "nau8825"; then CODECS+=("nau8825"); fi
fi
log "Detected codecs: ${CODECS[*]:-unknown (run after audio driver loads)}"

# --- Get board description ---
PRODUCT=$(cat /sys/class/dmi/id/product_version 2>/dev/null || \
          cat /sys/class/dmi/id/product_name 2>/dev/null || echo "Unknown")

# --- Add to hardware_map.conf ---
KVER="default"
PATCH_DIR="none"
[[ "$PLATFORM" == "amd-stoneyridge" ]] && PATCH_DIR="amd-stoneyridge"

log "Adding to hardware_map.conf:"
ENTRY="${CODENAME}|${PLATFORM}|${KVER}|${PATCH_DIR}|${PRODUCT}"
log "  $ENTRY"

# Find the right section to insert into
echo "" >> "${REPO_DIR}/configs/hardware_map.conf"
echo "# Auto-added by add_device.sh on $(date)" >> "${REPO_DIR}/configs/hardware_map.conf"
echo "$ENTRY" >> "${REPO_DIR}/configs/hardware_map.conf"

# --- Create device config fragment ---
DEVICE_CFG="${REPO_DIR}/configs/device/${CODENAME}.cfg"
if [[ ! -f "$DEVICE_CFG" ]]; then
    log "Creating device fragment: $DEVICE_CFG"
    cat > "$DEVICE_CFG" << EOF
# =============================================================================
# DEVICE CONFIG FRAGMENT: ${CODENAME}
# Board: ${PRODUCT}
# Platform: ${PLATFORM} (inherits configs/platform/${PLATFORM}.cfg)
# Auto-generated by add_device.sh on $(date)
#
# Add device-specific config options below that DIFFER from the platform default.
# This file intentionally starts minimal - only add what's needed.
# =============================================================================

# Codecs detected on this board:
$(for codec in "${CODECS[@]}"; do echo "CONFIG_SND_SOC_${codec^^}=m"; done)

# Add device-specific overrides below:
EOF
fi

log ""
log "Done! New device added:"
log "  Hardware map: $ENTRY"
log "  Device config: $DEVICE_CFG"
log ""
log "Next steps:"
log "  1. Review and edit $DEVICE_CFG if needed"
log "  2. Run: sudo ./scripts/build_kernel.sh --codename $CODENAME"
if [[ "$PLATFORM" == "amd-stoneyridge" ]]; then
    log ""
    log "  IMPORTANT (Stoneyridge): Ensure patches/amd-stoneyridge/ contains"
    log "  the DW I2S revert patch before building."
    log "  See patches/amd-stoneyridge/README for details."
fi
